default: &default
  adapter: postgresql

development:
  <<: *default
  database: menu_development
  username: postgres
  password: password

test: &test
  <<: *default
  database: menu_test
  username: postgres
  password: password

production:
  <<: *default
  database: menu


cucumber:
  <<: *test
